name: Deploy staging

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        # language=sh
        run: |
          echo "Secrets: ${{ toJson(secrets) }}"

          if [ "${{ secrets.ENVIRONMENT }}" == "unknown" ]; then
            exit 0
          else 
            exit 1
          fi

  deploy:
    environment: staging
    runs-on: ubuntu-latest
    needs: foo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check secrets
        # language=sh
        run: |
          echo "Secrets: ${{ toJson(secrets) }}"
          
          if [ "${{ secrets.ENVIRONMENT }}" == "staging" ]; then
            echo "Running in staging"
            exit 0
          else 
            exit 1
          fi

      - name: Deploy to staging
        run: echo "Deploying to staging"
